"""Copy the static project-review viewer (web/project/) into an OUT directory (the site root).

    python3 -m kipr.project.site --out OUT [--no-offline]

OUT already holds project-review.json and p/<slug>/... from `kipr project`; this adds index.html,
viewer.css, js/, vendor/ (the gerber renderer) and pcba3d/ (the 3D module, when built) next to them.
It never modifies the data files. Stdlib only.

Unless --no-offline is given it also makes the site work when opened straight from disk (file://,
e.g. an unzipped CI artifact), where browsers block fetch() and ES modules:
    js/bundle.js        the viewer's ES modules as one classic script
    data.js             window.KIPR_DATA = {review}
    offline/<slug>.js   per project: the SVG exports (schematic sheets, PCB layers) as text, so the
                        pixel diffs can draw them into a canvas without tainting it
    serve.py            tiny local web server (127.0.0.1, random port) for full http mode
    README.txt          how to open the report
The gerber (WebAssembly) and 3D views need http; from disk they say to run serve.py.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import quote

WEB = Path(__file__).resolve().parent.parent.parent / "web" / "project"
FILES = ["index.html", "viewer.css"]
DIRS = ["js", "vendor", "pcba3d"]
DATA_NAMES = {"project-review.json", "p", "project-review.html"}
SLUG_RE = re.compile(r"^[a-z0-9_-]{1,100}$")
MAX_PACK_FILE = 20 * 1024 * 1024
ENTRY = "app.js"

# --- bundle: ES modules -> one classic script (same scheme as the library viewer's build_site.py) ---

IMPORT_RE = re.compile(r"^import\s*\{([^}]*)\}\s*from\s*['\"](\./[A-Za-z0-9_.-]+\.js)['\"];?[ \t]*$", re.M)
EXPORT_RE = re.compile(r"^export\s+(?:(async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)|(const|let|var|class)\s+([A-Za-z_$][\w$]*))", re.M)
DYN_IMPORT_RE = re.compile(r"\bimport\(\s*['\"](\./[A-Za-z0-9_.-]+\.js)['\"]\s*\)")
# import('../vendor/...') / import('../pcba3d/...') stay dynamic imports: they only run over http(s)
# (the views check OFFLINE first), and a dynamic import() is valid in a classic script.


def transform_module(name: str, src: str) -> str:
    """Body of one module as a function(__exports) for the bundle. Handles the forms the viewer uses
    (named imports from './x.js', `export function|const|let|class`, import('./x.js'), import.meta.url)
    and refuses anything else so a new construct can't silently break the file:// build."""
    def imp(m):
        names = []
        for part in m.group(1).split(","):
            part = part.strip()
            if not part:
                continue
            a = re.fullmatch(r"([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?", part)
            if not a:
                raise ValueError(f"{name}: unsupported import specifier {part!r}")
            names.append(f"{a.group(1)}: {a.group(2)}" if a.group(2) else a.group(1))
        return f"const {{ {', '.join(names)} }} = __require({json.dumps(m.group(2))});"

    body = IMPORT_RE.sub(imp, src)
    exports = []

    def exp(m):
        exports.append(m.group(2) or m.group(4))
        return m.group(0)[len("export"):].lstrip()

    body = EXPORT_RE.sub(exp, body)
    body = DYN_IMPORT_RE.sub(lambda m: f"Promise.resolve().then(() => __require({json.dumps(m.group(1))}))", body)
    body = body.replace("import.meta.url", f"new URL({json.dumps('js/' + name)}, document.baseURI).href")
    leftover = re.search(r"^\s*(import\s|export\s)", body, re.M)
    if leftover:
        line = body[leftover.start():].splitlines()[0]
        raise ValueError(f"{name}: unsupported module syntax for the file:// bundle: {line.strip()!r}")
    tail = f"\n  Object.assign(__exports, {{ {', '.join(exports)} }});" if exports else ""
    return f"__defs[{json.dumps('./' + name)}] = function (__exports) {{\n'use strict';\n{body}{tail}\n}};\n"


def make_bundle(js_dir: Path) -> str:
    parts = ["// Generated by kipr/project/site.py from js/*.js for file:// use (classic script, no ES modules).",
             "// Do not edit; edit the modules and rebuild.",
             "(function () {", "'use strict';",
             "const __defs = {};", "const __cache = {};",
             "function __require(n) {",
             "  if (!__cache[n]) { if (!__defs[n]) throw new Error('bundle: no module ' + n);"
             " __cache[n] = {}; __defs[n](__cache[n]); }",
             "  return __cache[n];", "}"]
    for f in sorted(js_dir.glob("*.js")):
        if f.name in ("boot.js", "bundle.js"):
            continue
        parts.append(transform_module(f.name, f.read_text(encoding="utf-8")))
    parts.append(f"__require({json.dumps('./' + ENTRY)});")
    parts.append("}());")
    return "\n".join(parts) + "\n"


# --- data.js and per-project packs ---------------------------------------------------------------

def js_literal(value) -> str:
    """JSON that is also safe inside any HTML/JS context: no raw <, >, &, U+2028/9."""
    s = json.dumps(value, ensure_ascii=True, separators=(",", ":"))
    return s.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")


def asset_url(p: str) -> str:
    """Same encoding as assetUrl() in js/util.js (encodeURIComponent per segment)."""
    return "/".join(quote(seg, safe="!~*'()") for seg in p.split("/"))


def confined_file(out: Path, rel, slug: str | None = None) -> Path | None:
    """out/rel if rel is a plain relative path to a regular file inside out (and inside p/<slug>/ when
    slug is given), else None. Paths in the review come from a pull request."""
    if not isinstance(rel, str) or not rel or "\\" in rel or "\x00" in rel or rel.startswith("/"):
        return None
    if re.match(r"^[a-z][a-z0-9+.-]*:", rel, re.I) or any(seg in ("", ".", "..") for seg in rel.split("/")):
        return None
    if slug is not None and not rel.startswith(f"p/{slug}/"):
        return None
    base = out.resolve()
    p = (base / rel).resolve()
    if base not in p.parents or not p.is_file():
        return None
    return p


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def project_svgs(project: dict) -> list[str]:
    """Every SVG path the pixel diffs may rasterise: schematic sheets and PCB layer exports."""
    out = []
    sch = project.get("schematic") if isinstance(project.get("schematic"), dict) else {}
    for s in sch.get("sheets") or []:
        if isinstance(s, dict):
            out += [s.get("base"), s.get("head")]
    pcb = project.get("pcb") if isinstance(project.get("pcb"), dict) else {}
    for layer in pcb.get("layers") or []:
        if isinstance(layer, dict):
            for side in ("base", "head"):
                if isinstance(layer.get(side), dict):
                    out.append(layer[side].get("svg"))
    seen, uniq = set(), []
    for p in out:
        if isinstance(p, str) and p.endswith(".svg") and p not in seen:
            seen.add(p)
            uniq.append(p)
    return uniq


def build_offline(out: Path) -> dict:
    stats = {"data_js": 0, "packs": 0, "pack_bytes": 0, "skipped": []}
    review = load_json(out / "project-review.json")
    offline = out / "offline"
    if offline.exists():
        shutil.rmtree(offline)
    if not isinstance(review, dict):
        return stats  # the viewer shows its "no data" page
    for proj in review.get("projects") or []:
        if not isinstance(proj, dict):
            continue
        slug = proj.get("slug")
        if not isinstance(slug, str) or not SLUG_RE.match(slug):
            continue
        files = {}
        for rel in project_svgs(proj):
            fp = confined_file(out, rel, slug)
            if not fp:
                continue
            if fp.stat().st_size > MAX_PACK_FILE:
                stats["skipped"].append(rel)
                continue
            files[asset_url(rel)] = {"text": fp.read_bytes().decode("utf-8", errors="replace")}
        if files:
            offline.mkdir(exist_ok=True)
            js = (f"// Generated by kipr/project/site.py: offline copies of {slug}'s SVG exports.\n"
                  f"(window.KIPR_PACKS = window.KIPR_PACKS || {{}})[{js_literal(slug)}] = {js_literal({'files': files})};\n")
            (offline / f"{slug}.js").write_text(js, encoding="ascii")
            stats["packs"] += 1
            stats["pack_bytes"] += len(js)
    data_js = ("// Generated by kipr/project/site.py: review data for file:// use.\n"
               f"window.KIPR_DATA = {js_literal({'review': review})};\n")
    (out / "data.js").write_text(data_js, encoding="ascii")
    stats["data_js"] = len(data_js)
    return stats


# --- site ------------------------------------------------------------------------------------------

def build_site(out, offline: bool = True, web: Path = WEB) -> list[str]:
    """Copy the viewer into `out` (created if needed); returns the copied paths relative to out."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    copied = []
    for name in FILES:
        shutil.copy2(web / name, out / name)
        copied.append(name)
    for d in DIRS:
        src = web / d
        dst = out / d
        if dst.name in DATA_NAMES:
            raise RuntimeError(f"refusing to overwrite data dir {dst}")
        if dst.exists():
            shutil.rmtree(dst)
        if not src.is_dir():
            continue
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns("*.map", ".*", "bundle.js", "node_modules", "test", "tests"))
        copied += [str(p.relative_to(out)) for p in sorted(dst.rglob("*")) if p.is_file()]
    if offline:
        (out / "js" / "bundle.js").write_text(make_bundle(web / "js"), encoding="utf-8")
        shutil.copy2(web / "serve.py", out / "serve.py")
        shutil.copy2(web / "README.site.txt", out / "README.txt")
        copied += ["js/bundle.js", "serve.py", "README.txt"]
    else:
        for stale in ("data.js", "serve.py", "README.txt"):
            (out / stale).unlink(missing_ok=True)
        if (out / "offline").is_dir():
            shutil.rmtree(out / "offline")
    (out / ".nojekyll").touch()  # GitHub Pages: serve files as-is
    return copied


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", required=True, type=Path, help="site root (the `kipr project` OUT dir)")
    ap.add_argument("--no-offline", action="store_true",
                    help="skip the file:// support files (data.js, js/bundle.js, offline/, serve.py, README.txt)")
    args = ap.parse_args(argv)
    try:
        copied = build_site(args.out, offline=not args.no_offline)
        stats = build_offline(args.out) if not args.no_offline else None
    except (OSError, ValueError, RuntimeError) as e:
        print(f"kipr site: failed: {e}", file=sys.stderr)
        return 1
    print(f"kipr site: copied {len(copied)} viewer files into {args.out}")
    if stats:
        print(f"kipr site: file:// support: data.js {stats['data_js'] / 1024:.0f} KiB, "
              f"{stats['packs']} SVG pack(s) {stats['pack_bytes'] / 1024:.0f} KiB"
              + (f", skipped (too large): {', '.join(stats['skipped'])}" if stats["skipped"] else ""))
    if not (args.out / "project-review.json").exists():
        print(f"kipr site: warning: {args.out}/project-review.json not found; the viewer will show an error page", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
